# Generated by Django 4.2.9 on 2024-02-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
