# Generated by Django 4.2.9 on 2024-08-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='tab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tab'),
        ),
        migrations.AddField(
            model_name='event',
            name='tab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tab'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tab'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tab'),
        ),
    ]
